### ISSUE TITLE
ImportError: cannot import name '_unique_state_dict'

### ISSUE THREAD

**Issue by CommanderDuck** [nerox8664/pytorch2keras#10]
It seems like https://github.com/nerox8664/pytorch2keras/commit/49dc427e2c196a334dc7b173ff317e05f04813e7 breaks 0.2 compatibility  

```
ImportError                               Traceback (most recent call last)
<ipython-input-9-9e4002883d78> in <module>()
      1 import sys
      2 sys.path.insert(0, '../pytorch2keras/pytorch2keras')
----> 3 from converter import pytorch_to_keras
      4 k_model = pytorch_to_keras(model, x, (3, 224, 224), verbose=True)
      5 #we should specify shape of the input tensor

~/projects/pytorch2keras/pytorch2keras/converter.py in <module>()
      8 import torch.serialization
      9 import contextlib
---> 10 from torch.jit import _unique_state_dict
     11 
     12 from layers import AVAILABLE_CONVERTERS

ImportError: cannot import name '_unique_state_dict'
```

_unique_state_dict was added in 0.4 version: https://github.com/pytorch/pytorch/commit/e6cbe84bf679111316590efb4fd31ba195867a57

**Comment by nerox8664** [comment]
Hello @CommanderDuck. 
Yes, the new version of converter is no longer support the PyTorch 0.2. 
There is very different approach to traverse the graph and different weights/nodes structure. As a result, the new converter version (for PyTorch 0.4) has other code base.
If you want to use converter for version 0.2, please, use a corresponding tag.

P.S. Maybe a bit later i'll write converters for recurrent layers and commit them to new branch for the v0.2.
