### ISSUE TITLE
Share weights file？

### ISSUE THREAD

**Issue by bityangke** [nerox8664/pytorch2keras#14]
Hi
Have there anybody successfully transferred the weights file to Keras?
Could you please share ResNet18 keras weights?
Thx!

**Comment by nerox8664** [comment]
Hi @bityangke. 
The ResNet18 model is successfully transferred! You can check it in the `tests/` directory:
https://github.com/nerox8664/pytorch2keras/blob/master/tests/resnet18.py
If you already have pretrained model, just simply load it before convertation.

**Comment by bityangke** [comment]
@nerox8664 Thanks very much！
