### ISSUE TITLE
KeyError: u'prim::PythonOp'

### ISSUE THREAD

**Issue by Ai-is-light** [nerox8664/pytorch2keras#18]
When I convert the customized network from Pytorch to Keras-tensorflow, the error is following:
Traceback (most recent call last):
  File "pytorch_fpn-res2keras-tf.py", line 26, in <module>
    keras_model = pytorch_to_keras(pytorch_model, input_var, (3, 384, 384), verbose=True)
  File "/data/xxxx/framework_exchange/pytorch2keras/pytorch2keras/converter.py", line 160, in pytorch_to_keras
    AVAILABLE_CONVERTERS[node_type](
KeyError: u'prim::PythonOp'

@nerox8664 @justasbr
Looking forward to any replies. Thanks

**Comment by Ai-is-light** [comment]
('graph node:', u'DataParallel')
('type:', u'prim::PythonOp')
('inputs:', ['input'])
('outputs:', [u'DataParallel', u'DataParallel'])
('name in state_dict:', '')
('attrs:', {u'inplace': 0})
('is_terminal:', False)
Traceback (most recent call last):
  File "pytorch_fpn-res2keras-tf.py", line 26, in <module>
    keras_model = pytorch_to_keras(pytorch_model, input_var, (3, 384, 384), verbose=True)
  File "/data/xxxxx/framework_exchange/pytorch2keras/pytorch2keras/converter.py", line 160, in pytorch_to_keras
    AVAILABLE_CONVERTERS[node_type](
KeyError: u'prim::PythonOp'

**Comment by Ai-is-light** [comment]
Have you test the model trained under the multi-gpus with DataParallel method ???? I guess this error may be caused by the dataparallel training with pytorch

**Comment by nerox8664** [comment]
Hello there.
You can extract the actual model from DataParallel with:
`model = model.cpu().module`
and try to convert it again.

**Comment by Ai-is-light** [comment]
Thanks for your kindness reply.

**Comment by Ai-is-light** [comment]
After fix the error of "u'prim::PythonOp" , I got the following error
ValueError: Shape must be rank 1 but is rank 4 for 'resnet.bn10.162173865941/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,64,192,192], [1,64,1,1], [1,64,1,1], [1,64,1,1], [1,64,1,1].
I'm confused with the this ValueError
