### ISSUE TITLE
ERROR!!!! When I run the converted model , it always got terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by Ai-is-light** [nerox8664/pytorch2keras#19]
@nerox8664 Hi guys, after successfully getting the converted model, I got the error as following:
Using TensorFlow backend.
2018-06-28 11:24:45.607236: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-28 11:24:46.300184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:88:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-06-28 11:24:46.300260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-28 11:24:46.914014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-28 11:24:46.914079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-28 11:24:46.914088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-28 11:24:46.914566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10390 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:88:00.0, compute capability: 6.1)
/home/wupeng/workshop/fashion-keypoint/venv-kp/local/lib/python2.7/site-packages/keras/models.py:252: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
('image_path  :', './data/train_0427/Images/dress/ca8b38cc7fb0ce9e35563766d12090b7.jpg')
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by Ai-is-light** [comment]
More details. I successfully converted the pytorch model to keras/tensorflow model. And, after I got the converted keras-tensorflow model, I test this as input as input_np = np.random.uniform(0, 1, (1, 3, 384, 384)). The ouput of the  keras-tensorflow model is almost the same as the original pytorch model. However, when I test this  keras-tensorflow model under the images as input, it broke down as following the error as above.

Thanks
Looking forward any replies. @nerox8664 @justasbr 
Sincerely

**Comment by nerox8664** [comment]
Hello there.

```
oriImg.shape---0 : (512, 512, 3)
scale : 0.7
imageToTest.shape---> : (358, 358, 3)
imgToTest_padded ---> : (384, 384, 3)
```

Looks like you try to run CHW model with HWC image. Please, check image dimension ordering and try again.
Furthermore, you can change the model ordering with corresponding converter option.

**Comment by Ai-is-light** [comment]
Ok, I will check it. However, I'm not similar to the tensorflow and keras, and would you mind explaining more details about the following setting：
...
"backend": "tensorflow",
"image_data_format": "channels_first",
...
And，this setting is related to the model ordering ?

**Comment by Ai-is-light** [comment]
as for the fully convolutional network, the size of input is not fixed. And I found that the converted keras-tensorflow model need the FIXED input size, for example, I got the transformed model of the  input_np = np.random.uniform(0, 1, (1, 3, 384, 384)), and keras_model = pytorch_to_keras(pytorch_model, input_var, (3, 384, 384), verbose=False). If I would like to maintain the changeable input character of the fully convolutional network, how can I do that??

**Comment by Ai-is-light** [comment]
@nerox8664 
as for the fully convolutional network, the size of input is not fixed. And I found that the converted keras-tensorflow model need the FIXED input size, for example, I got the transformed model of the  input_np = np.random.uniform(0, 1, (1, 3, 384, 384)), and keras_model = pytorch_to_keras(pytorch_model, input_var, (3, 384, 384), verbose=False). If I would like to maintain the changeable input character of the fully convolutional network, how can I do that??

**Comment by nerox8664** [comment]
hello @Ai-is-light. 
You can check the new version. Models with not specified spatial dimensions are now supported by the converter.
