### ISSUE TITLE
Do you have any plan to support slicing (or narrow layer) layer?

### ISSUE THREAD

**Issue by ChunfeiMa** [nerox8664/pytorch2keras#25]
I was converting a model which using ResNet50 as backbone following by some slicing and avg pool and conv operation, but the problem is that it seems the "onnx::Slice" layer is not supported in the current version therefore results in the converting error. So I'd like to know if you are going to add the functionality for converting the slice layer?

**Comment by nerox8664** [comment]
Hello, @ChunfeiMa!
Yep I have a plan to implement almost all core layers and operations, so, I'll do it as soon as possible.

**Comment by nerox8664** [comment]
Please, check the latest [commit in master](https://github.com/nerox8664/pytorch2keras/commit/bbdfdfeae6fde40623ac7672fa705f0b97251c21).
Does it work for you?

**Comment by ChunfeiMa** [comment]
@nerox8664  That's exactly what I want, thanks for your effort. I will check if it works.
