### ISSUE TITLE
NEW ErrorUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1124: ordinal not in range(128)

### ISSUE THREAD

**Issue by Ai-is-light** [nerox8664/pytorch2keras#28]
Using TensorFlow backend.
Traceback (most recent call last):
  File "pytorch_fpn-res2keras-tf.py", line 18, in <module>
    pytorch_model = torch.load('./_0620_80000.pth')
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1124: ordinal not in range(128)
@nerox8664 would u mind sharing all of your environment? I mean, for example, numpy'version included. The repo work well about a mouth ago, but now, it doesn't work. And, I have upgraded something for the past a mouth.
Thanks.
looking forward to any replies.

**Comment by nerox8664** [comment]
Hello @Ai-is-light.
I've updated requirements.txt with my package versions.
So, as far as i can see, your problem related to the PyTorch version. When you pickle/unpickle a whole object (not only weights) some problems like that may occur.

**Comment by Ai-is-light** [comment]
Thanks for your reply， I will have a try. I have one more question. The model I will deal with is trained by torch --0.3.1 & torchvision -0.2.1, so , I succeed in transforming from the pytorch's model to keras-tensorflow's model with torch-0.3.1. So, I wonder that your proposal's torch's version is 0.4.0, the torch's 0.4.0 will work with the 0.3.1 versions torch's model?

**Comment by nerox8664** [comment]
Hello @Ai-is-light.
Are you trying to pickle/unpickle your model or just load the weights? Pickled models are supported only by with version they were pickled. About BatchNorm2d: in the 0.4 release API of BatchNorm2d was slightly changed, so, you can fix the definition and load the model.
