### ISSUE TITLE
about the branch about supporting pytorch0.3.0 or 0.3.1

### ISSUE THREAD

**Issue by Ai-is-light** [nerox8664/pytorch2keras#30]
after reading all the issue, there was the branch which could support the pytorch0.3.0,
would you mind sharing this branch again.
Thanks
@nerox8664

**Comment by nerox8664** [comment]
Hello @Ai-is-light.
Pytorch 0.3* was never supported because of broken grad_fn and not complete ONNX, so, there wasn't any way to traverse graph and get weights layer-by-layer.

As far as i know, Pytorch has kind of backward compatibility, and you can run your 0.3* model on 0.4 as well.
