### ISSUE TITLE
All layer names has been changed

### ISSUE THREAD

**Issue by shuguohe** [nerox8664/pytorch2keras#36]
During transfer, all layer names are changed, so it is confused to use because it is hard to find the layer name match the standard resnet101 name

**Comment by nerox8664** [comment]
hello @shuguohe
Yep, it's a problem. I think about a new option `keep_names` or something like that. So, a random suffixes are an ad-hoc solution for now because pytorch graph can contain multiple layers with same name, but it's prohibited for tensorflow graph

**Comment by nerox8664** [comment]
Hi @shuguohe. I added a new option `names` to convertor parameters. You can use it with `names='keep'` to keep the original layers names.
