### ISSUE TITLE
pytorch 0.3

### ISSUE THREAD

**Issue by auroua** [nerox8664/pytorch2keras#4]
After upgrade `pytorch` to version 0.3, the test file `alexnet.py` can not work correctly. How to solve this problem?

**Comment by nerox8664** [comment]
Hello @auroua. I've checked the new PyTorch and yes, something in the graph computation was changed. If you want to use this converter I only advise to downgrade your PyTorch version.

I noticed these changes:
1. https://github.com/nerox8664/pytorch2keras/blob/master/pytorch2keras/converter.py#L37 Is no longer accurate. There is some questions about new structure. For example, for Linear / Dense I've a new nodes `ExpandBackward`. So, I'm trying to figure it out.
2. Layer names was also changed.

**Comment by auroua** [comment]
Do you planning to support `pytorch 0.3`?
