### ISSUE TITLE
problem with loading the keras model 

### ISSUE THREAD

**Issue by cnaaq** [nerox8664/pytorch2keras#44]
Hi,

I followed the instruction to get keras model from a torch model. It is (probably) successful, and I save it and everything till here is just fine.
However, when I try to load again the saved keras model, I get the following error:

`Using TensorFlow backend.`
`2018-12-13 11:49:04.256785: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`
`Traceback (most recent call last):`
`  File "D:/Github packages/deep-head-pose-master-python3/deep-head-pose-master/core2/testing.py", line 4, in <module>`
`    model = keras.models.load_model('keras_model.h5')`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\engine\saving.py", line 419, in load_model`
`    model = _deserialize_model(f, custom_objects, compile)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model`
`    model = model_from_config(model_config, custom_objects=custom_objects)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\engine\network.py", line 991, in process_node
   layer(unpack_singleton(input_tensors), **kwargs)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)`
`  File "C:\Users\cnq\AppData\Local\Continuum\miniconda3\envs\torch_new\lib\site-packages\pytorch2keras-0.1.12-py3.6.egg\pytorch2keras\layers.py", line 1330, in target_layer
    def target_layer(x):`
`NameError: name 'keras' is not defined`

Any idea?

 - OS: Win 7
 - Python 3.6
 - Version [e.g. v0.1.11]

**Comment by nerox8664** [comment]
hi @cnaaq! You probably have to add `import keras` at the top of your script and then try to do conversion / load again.

**Comment by cnaaq** [comment]
Hi @nerox8664  and thanks for your quick reply :)

Actually, I tried what you said, and I even tried upgrading python, reinstalling keras (and tensorflow), but it didn't help.

**Comment by cnaaq** [comment]
if it has happened only to me, then probably **bug** label should be removed, but I don't know how to remove it.

**Comment by nerox8664** [comment]
can you show the code of your model to give me a chance to reproduce the error?

**Comment by cnaaq** [comment]
of course! actually, the pytorch model is this repository that I want to bring it to keras: https://github.com/cleardusk/3DDFA
in main.py file and inside main method, first the saved pytorch model is loaded.
I just got `model` there, and tried to bring it to keras:

`input_np = np.random.uniform(0, 1, (1, 3, 32, 32))`
`input_var = torch.autograd.Variable(torch.FloatTensor(input_np))`
`k_model = pytorch_to_keras(model, input_var, [(3, None, None)], verbose=True)` 

I get the keras model and can save it. But as mentioned above, I cannot load it afterwards...

**Comment by nerox8664** [comment]
I reproduced this issue. Yes, here is something weird with lambda layers after loading. You can check it now (the latest commit in master).
To make it work you have to convert the model again (to apply new lambda layers) and then try to load it.

**Comment by cnaaq** [comment]
wow! Thank you very much! Problem solved :)
