### ISSUE TITLE
Error in AlexNet test

### ISSUE THREAD

**Issue by bayesrule** [nerox8664/pytorch2keras#46]
**Describe the bug**
When running the provided test for AlexNet, encountered KeyError: 'classifier.0.weight'

I checked what keys does weights dict have:

odict_keys(['features.0.weight', 'features.0.bias', 'features.3.weight', 'features.3.bias', 'features.6.weight', 'features.6.bias', 'features.8.weight', 'features.8.bias', 'features.10.weight', 'features.10.bias', 'classifier.1.weight', 'classifier.1.bias', 'classifier.4.weight', 'classifier.4.bias', 'classifier.6.weight', 'classifier.6.bias'])

**To Reproduce**
Simply run pytorch2keras/tests/models/alexnet.py

**Logs**
....
....
....                                                                                                             
Converting flatten ...                                                                                                                
 ____                                                                                                                                 
graph node: AlexNet/Sequential[classifier]/Dropout[0]                                                                                 
node id: 104                                                                                                                          
type: onnx::Dropout                                                                                                                   
inputs: ['101']                                                                                                                       
outputs: ['AlexNet/Sequential[classifier]/Dropout[0]', 'AlexNet/Sequential[classifier]/Dropout[0]']                                   
name in state_dict: classifier.0                                                                                                      
attrs: {'ratio': 0.5}                                                                                                                 
is_terminal: False                                                                                                                    
Converting dropout ...                                                                                                                
 ____                                                                                                                                 
graph node: AlexNet/Sequential[classifier]/Dropout[0]                                                                                 
node id: 109                                                                                                                          
type: onnx::Gemm                                                                                                                      
inputs: ['104', 'input11', 'input12']                                                                                                 
outputs: ['AlexNet/Sequential[classifier]/Dropout[0]']                                                                                
name in state_dict: classifier.0                                                                                                      
attrs: {'alpha': 1.0, 'beta': 1.0, 'transB': 1}                                                                                       
is_terminal: False                                                                                                                    
Converting Linear ...                                                                                                                 
Traceback (most recent call last):                                                                                                    
  File "validate_cnn.py", line 39, in <module>                                                                                        
    k_model = pytorch_to_keras(model, input_var, (3, 224, 224,), verbose=True)                                                        
  File "C:\Users\xxxxxx\work\WPy-3670\python-3.6.7.amd64\lib\site-packages\pytorch2keras\converter.py", line 325, in pytorch_to_keras
    names                                                                                                                             
  File "C:\Users\xxxxxx\work\WPy-3670\python-3.6.7.amd64\lib\site-packages\pytorch2keras\linear_layers.py", line 34, in convert_gemm 
    W = weights[weights_name].numpy().transpose()                                                                                     
KeyError: 'classifier.0.weight' 

                                                                       
**Environment (please complete the following information):**
 - OS: Windows 7
 - Python 3.6, PyTorch 1.0
 - Latest pytorch2keras master

**Comment by nerox8664** [comment]
Hello @bayesrule.
Yes, I reproduced this issue with PyTorch version 1.0 (the previous 0.4.1 works well).
