### ISSUE TITLE
question

### ISSUE THREAD

**Issue by superCman** [nerox8664/pytorch2keras#48]
File "/usr/local/lib/python3.5/dist-packages/pytorch2keras/reshape_layers.py", line 122, in target_layer
    return tf.squeeze(x, axis=axis)
NameError: name 'tf' is not defined
why happen to it，please！

**Comment by nerox8664** [comment]
Hello @superCman! 
Did it happen when you try to load your model?
I added extra imports for lambdas in reshape layers. Can you pull the latest master commit and try to convert / load your model again?

**Comment by superCman** [comment]
@nerox8664 thx, when i pull the latest master,it works well.
