### ISSUE TITLE
can't pickle SwigPyObject objects

### ISSUE THREAD

**Issue by NoushNabi** [nerox8664/pytorch2keras#49]
Thank you very much for your code. 
I was able to convert my pytorch model to keras successfully. The summary of model was also correct. But when I wanted to save the keras model, I received the below error. I searched but didn't find anything useful. I appreciate any advice or suggestions. 

TypeError: can't pickle SwigPyObject objects

Thanks,
Noosh

**Comment by nerox8664** [comment]
Hello @NoushNabi. Can you show me your code for conversion and loading?

**Comment by NoushNabi** [comment]
`
def main(cfg):
    module = importlib.import_module("model.{}".format(cfg.model))  #it imports model.carn.py
    net = module.Net(multi_scale=True,  group=cfg.group)
    state_dict = torch.load(cfg.ckpt_path, map_location='cpu')
    new_state_dict = OrderedDict()
    for k, v in state_dict.items():
        name = k
        new_state_dict[name] = v

    net.load_state_dict(new_state_dict)
    scale = cfg.scale
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = net.to(device)
    
    # create a dummy variable with correct shape:
    input_np = np.random.uniform(0, 1, (1, 3, 32, 32))
    input_var = Variable(torch.FloatTensor(input_np))
    
    import pytorch2keras.pytorch2keras.converter as con
    from converter import pytorch_to_keras
    k_model = pytorch_to_keras(model, input_var, [(3, 32, 32,)], verbose=True)
    k_model.summary()
    
    k_model.save('my_model.h5')
 

if __name__ == "__main__":
    cfg = parse_args()
    main(cfg)
`

**Comment by nerox8664** [comment]
Sorry for a big delay. Can you show me the model definition? And the code for model loading. Are you sure, your Keras version is compatible with your TensorFlow version?

**Comment by NoushNabi** [comment]
@nerox8664: Thank you for your reply and sorry for my big delay.
Yes, my Keras and TF versions are compatible and they work fine in other projects.
I am trying to convert the CARN model in this repository:
https://github.com/nmhkahn/CARN-pytorch

Your help is really appreciated.

**Comment by RylanSchaeffer** [comment]
@nerox8664 what happened? I have a similar error but I don't see a solution.

**Comment by xingcw** [comment]
@NoushNabi I got the same error, have you found solutions?
