### ISSUE TITLE
Error when importing torch._C.ListType

### ISSUE THREAD

**Issue by EloiZalczer** [nerox8664/pytorch2keras#53]
I am using Pytorch v0.4.1.post2. When executing my code, I get an ImportError saying that torch._C.ListType does not exist.

The error happens in converter.py. Basically the conditions used `if version.parse('0.4.1') < version.parse(torch.__version__)` should only be true if the user is using Pytorch>=1.0.0 but are also true for versions v0.4.1.x. 

I managed to work around this by replacing `if version.parse('0.4.1') < version.parse(torch.__version__)` with `if version.parse('1.0.0') <= version.parse(torch.__version__)`. I can PR if you want.

**Comment by nerox8664** [comment]
Hi @EloiZalczer!
Yeah, sure. Please, check the conditions with different PyTorch versions and then I will be happy to apply your PR :)
