### ISSUE TITLE
It's not working with Pytorch = 1.0

### ISSUE THREAD

**Issue by Golbstein** [nerox8664/pytorch2keras#58]
I've downgraded to 0.4.1 and it worked

**Comment by nerox8664** [comment]
Hello @Golbstein.
Yes, I plan to rewrite graph traverse function. It works for very simple models with PyTorch 1.0.
If you'll send me a log with errors, I can fix it in future.

**Comment by Golbstein** [comment]
Actually I think the problem is with my machine...

When I run this code in my laptop it works (windows) but when I run it on my linux server it throws me "`Segmentation fault (core dumped)`"  error. Do you know what's that?

**Comment by nerox8664** [comment]
Are you sure that PyTorch and Tensorflow works on your machine? My library doesn't have C-backend or any other low-level operations with memory.

**Comment by Golbstein** [comment]
yes
