### ISSUE TITLE
Hi i got this error: 

### ISSUE THREAD

**Issue by MNaseerSubhani** [nerox8664/pytorch2keras#62]
k_model = pytorch_to_keras(single_model, input_var, [(3, None, None,)], verbose=True) 

![1](https://user-images.githubusercontent.com/39435854/53019426-8abdf180-3476-11e9-960d-683640ca7d59.PNG)

**Comment by nerox8664** [comment]
hello @MNaseerSubhani . You try to convert model located in `CUDA` memory, or try to pass a tensor located in `CUDA` as an argument. Please, make sure both model and arguments are in `cpu` memory.

**Comment by MNaseerSubhani** [comment]
Thank you. got it
