### ISSUE TITLE
 Does it also support GPU version models?

### ISSUE THREAD

**Issue by pride0723** [nerox8664/pytorch2keras#67]
For the ResNet18 model, we confirmed that the CPU version of tensorflow, keras works well

But GPU version fails and does not work.

Can we fix the problem on GPU version?

 - OS: Ubuntu 16.04
 - Python : 3.6.7
 - Pytorch: 1.0.0
 - Tensorflow: 1.12

**Comment by nerox8664** [comment]
Hello @pride0723.
You can always move your GPU model to CPU memory and then convert it. The resulting Keras / Tensorflow model is device-agnostic.
