### ISSUE TITLE
"Getting Started" documentation unclear

### ISSUE THREAD

**Issue by pavelgrib** [nerox8664/pytorch2keras#73]
**Describe the bug**
The docs (https://pytorch2keras.readthedocs.io/en/latest/getting_started/) have a line that seems to be crucial to making the package work:
```
input_var = Variable(torch.FloatTensor(input_np))
```
but don't specify where this `Variable` object is imported from or defined.  Can you elucidate?

**Comment by nerox8664** [comment]
Hello @pavelgrib.

I updated getting started guide.
[https://pytorch2keras.readthedocs.io/en/latest/getting_started/](https://pytorch2keras.readthedocs.io/en/latest/getting_started/)
