### ISSUE TITLE
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

### ISSUE THREAD

**Issue by Brave731** [nerox8664/pytorch2keras#98]
**Describe the bug**
 File "/home/admin/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg     raise RuntimeError("Failed to export an ONNX attribute, "

**To Reproduce**
__Snippet of your code__

**Expected behavior**

**Logs**
If applicable, add error message to help explain your problem.

**Environment (please complete the following information):**
 - OS: centos
 - Python 3
 - Version [e.g. v0.1.11]

**Additional context**

**Comment by nerox8664** [comment]
Hello @Brave731.
It looks like the problem is in torch/onnx, not in the pytorch2keras.
